---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: scone-manager-role
  namespace: {{.Release.Namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - scone-operator-pull
  resources:
  - secrets
  verbs:
  - get
  - list