---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scone-serving-cert
  namespace: {{.Release.Namespace}}
spec:
  dnsNames:
  - scone-webhook-service.{{.Release.Namespace}}.svc
  - scone-webhook-service.{{.Release.Namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: scone-selfsigned-issuer
  secretName: webhook-server-cert