---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/scone-serving-cert
  name: scone-mutating-webhook-configuration-{{.Release.Namespace}}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: scone-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-base-scone-cloud-v1beta1-las
  failurePolicy: Fail
  name: mlas.kb.io
  rules:
  - apiGroups:
    - base.scone.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - las
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: scone-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-base-scone-cloud-v1beta1-sgxplugin
  failurePolicy: Fail
  name: msgxplugin.kb.io
  rules:
  - apiGroups:
    - base.scone.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sgxplugins
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: scone-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-services-scone-cloud-v1beta1-cas
  failurePolicy: Fail
  name: mcas.kb.io
  rules:
  - apiGroups:
    - services.scone.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: scone-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-services-scone-cloud-v1beta1-vault
  failurePolicy: Fail
  name: mvault.kb.io
  rules:
  - apiGroups:
    - services.scone.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaults
  sideEffects: None